doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

#        types:
#            purchase_type_enum: App\ProductCatalog\Purchase\Infrastructure\Doctrine\Type\PurchaseTypeEnumType
#        mapping_types:
#            purchase_type_enum: string
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App\ProductCatalog\Category:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/ProductCatalog/Part/Infrastructure/DoctrineMapping'
                prefix: 'App\ProductCatalog\Part\Domain\Entity'
                alias: Category
            App\ProductCatalog\Car:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/ProductCatalog/Car/Infrastructure/DoctrineMapping'
                prefix: 'App\ProductCatalog\Car\Domain\Entity'
                alias: Car
            App\Authorization:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Authorization/User/Infrastructure/DoctrineMapping'
                prefix: 'App\Authorization\User\Domain\Entity'
                alias: User
            App\ProductCatalog\Service:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/ProductCatalog/Service/Infrastructure/DoctrineMapping'
                prefix: 'App\ProductCatalog\Service\Domain\Entity'
                alias: Service
            config:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/config/doctrine/Money'
                prefix: 'Money'
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
