<?php

namespace App\ProductCatalog\Car\Infrastructure\DataFixtures;

use App\ProductCatalog\Car\Domain\Entity\Brand;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class BrandFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $brands = $this->getBrands();
        foreach ($brands as $brandName) {
            $brand = new Brand($brandName);
            $manager->persist($brand);
        }

        $manager->flush();
    }

    private function getBrands(): array {
        return ["AC",
            "Abarth",
            "Acura",
            "Adler",
            "Aito",
            "Aixam",
            "Alfa Romeo",
            "Alpina",
            "Alpine",
            "Ambertruck",
            "Arcfox",
            "Aro",
            "Asia",
            "Aston Martin",
            "Audi",
            "Aurus",
            "Austin",
            "Avatr",
            "BAIC",
            "BAW",
            "BMW",
            "BYD",
            "Bajaj",
            "Baltijas Dzips",
            "Baojun",
            "Belgee",
            "Bentley",
            "Brilliance",
            "Bugatti",
            "Buick",
            "CHERY",
            "Cadillac",
            "Changan",
            "Changfeng",
            "Chevrolet",
            "Chrysler",
            "Ciimo (Dongfeng-Honda)",
            "Citroen",
            "Coda",
            "Cupra",
            "DS",
            "DW Hower",
            "Dacia",
            "Dadi",
            "Daewoo",
            "Daihatsu",
            "Daimler",
            "Datsun",
            "Dayun",
            "DeLorean",
            "Delage",
            "Denza",
            "Derways",
            "Dodge",
            "Dongfeng",
            "Doninvest",
            "EXEED",
            "Eagle",
            "Enovate (Enoreve)",
            "Everus",
            "Evolute",
            "Excalibur",
            "FAW",
            "FSO",
            "Facel Vega",
            "Ferrari",
            "Fiat",
            "Ford",
            "Forthing",
            "Foton",
            "GAC",
            "GAC Aion",
            "GAC Trumpchi",
            "GMC",
            "Geely",
            "Genesis",
            "Geo",
            "Great Wall",
            "Hafei",
            "Haima",
            "Haval",
            "Hawtai",
            "Hennessey",
            "HiPhi",
            "Honda",
            "Hongqi",
            "Hozon",
            "HuangHai",
            "Hudson",
            "Hummer",
            "Hycan",
            "Hyundai",
            "IM Motors (Zhiji)",
            "Ineos",
            "Infiniti",
            "Innocenti",
            "International Harvester",
            "Iran Khodro",
            "Isuzu",
            "JAC",
            "JMC",
            "Jaecoo",
            "Jaguar",
            "Jeep",
            "Jetour",
            "Jetta",
            "Jidu",
            "Jinbei",
            "KG Mobility",
            "Kaiyi",
            "Kawei",
            "Kia",
            "Knewstar",
            "Koenigsegg",
            "LEVC",
            "Lada (ВАЗ)",
            "Lamborghini",
            "Lancia",
            "Land Rover",
            "Landwind",
            "Leapmotor",
            "Lexus",
            "LiXiang",
            "Liebao Motor",
            "Lifan",
            "Lincoln",
            "Livan",
            "Lotus",
            "Lucid",
            "Luxeed",
            "Luxgen",
            "Lynk &amp; Co",
            "M-Hero",
            "MG",
            "Mahindra",
            "Maple",
            "Maserati",
            "Maxus",
            "Maybach",
            "Mazda",
            "McLaren",
            "Mercedes-Benz",
            "Mercury",
            "Metrocab",
            "Mini",
            "Mitsubishi",
            "Mitsuoka",
            "Morgan",
            "Nevo",
            "Nio",
            "Nissan",
            "OMODA",
            "Oldsmobile",
            "Opel",
            "Ora",
            "Oshan",
            "Oting",
            "Packard",
            "Pagani",
            "Peugeot",
            "Plymouth",
            "Polar Stone (Jishi)",
            "Polestar",
            "Pontiac",
            "Porsche",
            "Proton",
            "Puch",
            "Qoros",
            "Ram",
            "Ravon",
            "Reliant",
            "Renault",
            "Renault Samsung",
            "Rising Auto",
            "Rivian",
            "Roewe",
            "Rolls-Royce",
            "Rover",
            "Rox",
            "SEAT",
            "SWM",
            "Saab",
            "Sandstorm",
            "Saturn",
            "Scion",
            "Seres",
            "ShuangHuan",
            "Simca",
            "Skoda",
            "Skywell",
            "Smart",
            "Solaris",
            "Sollers",
            "Soueast",
            "SsangYong",
            "Stelato",
            "Steyr",
            "Subaru",
            "Suzuki",
            "TVR",
            "Tank",
            "Tata",
            "Tatra",
            "Tesla",
            "Tianma",
            "Tianye",
            "Tofas",
            "Toyota",
            "Trabant",
            "VGV",
            "Vauxhall",
            "Venucia",
            "Volkswagen",
            "Volvo",
            "Vortex",
            "Voyah",
            "Wanderer",
            "Wartburg",
            "Weltmeister",
            "Wey",
            "Willys",
            "Wuling",
            "Xcite",
            "Xiaomi",
            "Xin Kai",
            "Xpeng",
            "Yema",
            "Yulon",
            "ZX",
            "Zeekr",
            "Zotye",
            "iCar",
            "Амберавто",
            "ГАЗ",
            "ЗАЗ",
            "ЗИЛ",
            "ЗиС",
            "Иж",
            "Канонир",
            "Комбат",
            "ЛуАЗ",
            "Москвич",
            "СМЗ",
            "Спортивные авто и реплики",
            "ТагАЗ",
            "УАЗ",
            "AM General",
            "AMC",
            "Aiways",
            "Apal",
            "Ariel",
            "Auburn",
            "Austin Healey",
            "Auto Union",
            "Autobianchi",
            "Batmobile",
            "Bertone",
            "Bilenkin",
            "Bio Auto",
            "Bitter",
            "Blaval",
            "Borgward",
            "Brabus",
            "Bristol",
            "Bufori",
            "Byvin",
            "Callaway",
            "Carbodies",
            "Caterham",
            "Chana",
            "Changhe",
            "Cizeta",
            "Coggiola",
            "Cord",
            "DKW",
            "Dallara",
            "De Tomaso",
            "DeSoto",
            "Deco Rides",
            "Donkervoort",
            "E-Car",
            "Eagle Cars",
            "Exlantix",
            "Fisker",
            "Flanker",
            "Franklin",
            "Fuqi",
            "GMA",
            "GP",
            "Goggomobil",
            "Gonow",
            "Gordon",
            "HSV",
            "Hanomag",
            "Hanteng",
            "Heinkel",
            "Hindustan",
            "Hispano-Suiza",
            "Holden",
            "Horch",
            "Huaihai (Hoann)",
            "Huazi",
            "Hyperion",
            "Invicta",
            "Isdera",
            "Iveco",
            "JMEV",
            "Jensen",
            "Jiangnan",
            "Jonway",
            "KTM AG",
            "KYC",
            "Karma",
            "LTI",
            "Ligier",
            "Logem",
            "Marcos",
            "Marlin",
            "Marussia",
            "Maruti",
            "Matra",
            "Mega",
            "Messerschmitt",
            "Microcar",
            "Minelli",
            "Mobilize",
            "Morris",
            "Nash",
            "Noble",
            "Osca",
            "Overland",
            "PGO",
            "Panoz",
            "Perodua",
            "Piaggio",
            "Pierce-Arrow",
            "Premier",
            "Puma",
            "Punk",
            "Qiantu",
            "Qingling",
            "Qvale",
            "Radar",
            "Radford",
            "Rayton Fissore",
            "Renaissance",
            "Rezvani",
            "Rimac",
            "Rinspeed",
            "Ronart",
            "Rossa",
            "Saipa",
            "Saleen",
            "Santana",
            "Scout",
            "Sears",
            "Shanghai Maple",
            "Skyworth",
            "Spectre",
            "Spyker",
            "Studebaker",
            "Talbot",
            "Tazzari",
            "Thairung",
            "Think",
            "Tramontana",
            "Triumph",
            "Ultima",
            "VUHL",
            "Vector",
            "Venturi",
            "VinFast",
            "Volga",
            "W Motors",
            "Westfield",
            "Wiesmann",
            "XEV",
            "XiaoPaoChe (SSC)",
            "Yipai",
            "Zastava",
            "Zenos",
            "Zenvo",
            "Zibar",
            "lingxi",
            "Ё-мобиль",
            "Автокам",
            "Атом",
            "Руссо-Балт"];
    }
}
