POST http://localhost:8000/api/login
Content-Type: application/json

{"email":  "admin@admin.com", "password": "admin"}
####
####

GET http://localhost:8000/api/parts/categories/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MzI3MDUwMTYsImV4cCI6MTczMjc5MTQxNn0.k70_F82JNHV7lI69mocDphyuwdqQoT_auavWrsk8zik

####
GET http://localhost:8000/api/cars/brands
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MzI1MzY5MjQsImV4cCI6MTczMjU0MDUyNH0.32FxNt6CLkls6BjdjcWSy3YSGLcQwymQXHLBwMX6Fow

####
GET http://localhost:8000/api/cars/bmw/models
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3MzI1MzY5MjQsImV4cCI6MTczMjU0MDUyNH0.32FxNt6CLkls6BjdjcWSy3YSGLcQwymQXHLBwMX6Fow

#### Login as BMW user
POST http://localhost:8000/api/login
Content-Type: application/json

{"email":  "bmw-owner@admin.com", "password": "bmw-owner"}
### for mersedes owner user use: "mercedes-owner@admin.com:mercedes-owner"
###

GET http://localhost:8000/api/cars
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJibXctb3duZXJAYWRtaW4uY29tIiwiaWF0IjoxNzMyNTQ0NTM4LCJleHAiOjE3MzI1NDgxMzh9.HlfsN0QpLJQYAshC6rYYQNq3j2wiBhzpe1oy28aygr0
####
POST http://localhost:8000/api/products
Content-Type: application/json

{
  "category_id": "uuidv7",
  "name": "TRW 34243",
  "part_number": "111212121212",
  "car_id": "uuid"
}