POST http://localhost:8000/api/login
Content-Type: application/json

{"email":  "admin@admin.com", "password": "admin"}

> {% client.global.set("auth_token", response.body.token); %}
####
####

GET http://localhost:8000/api/parts/categories/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

####
GET http://localhost:8000/api/cars/brands
Content-Type: application/json
Authorization: Bearer {{auth_token}}

####
GET http://localhost:8000/api/cars/bmw/models
Content-Type: application/json
Authorization: Bearer {{auth_token}}

#### Login as BMW user
POST http://localhost:8000/api/login
Content-Type: application/json

{"email":  "bmw-owner@admin.com", "password": "bmw-owner"}

> {% client.global.set("auth_token", response.body.token); %}
### for mersedes owner user use: "mercedes-owner@admin.com:mercedes-owner"
###

GET http://localhost:8000/api/cars
Content-Type: application/json
Authorization: Bearer {{auth_token}}
####
POST http://localhost:8000/api/products
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "category_id": "uuidv7",
  "name": "TRW 34243",
  "part_number": "111212121212",
  "car_id": "uuid"
}