POST http://localhost:8000/api/login
Content-Type: application/json

{"email":  "admin@admin.com", "password": "admin"}

> {% client.global.set("auth_token", response.body.token); %}
####
####

GET http://localhost:8000/api/parts/categories/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

####
GET http://localhost:8000/api/cars/brands
Content-Type: application/json
Authorization: Bearer {{auth_token}}

####
GET http://localhost:8000/api/cars/bmw/models
Content-Type: application/json
Authorization: Bearer {{auth_token}}

#### Login as BMW user
POST http://localhost:8000/api/login
Content-Type: application/json

{"email":  "bmw-owner@admin.com", "password": "bmw-owner"}

> {% client.global.set("auth_token", response.body.token); %}
### for mersedes owner user use: "mercedes-owner@admin.com:mercedes-owner"


#### I want to add a new car
POST http://localhost:8000/api/cars
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "my car",
  "brand": "bmw",
  "model": "3-series",
  "vin": "vin number",
  "color": "color",
  "registrationNumber": "320 AAB",
  "producedAt": "19.04.2023"
}

### I want to see all cars
GET http://localhost:8000/api/cars
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###  I want to create a new service
POST http://localhost:8000/api/services
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "name": "oil change",
    "currency": "EUR",
    "car_id": "01944070-5e00-730f-a54c-140bed0077ca",
    "unit_price": 23.34,
    "quantity": 0.95
}

##### I want to see exists services
GET http://localhost:8000/api/services
Content-Type: application/json
Authorization: Bearer {{auth_token}}

#### I want to see part categories
GET http://localhost:8000/api/parts/categories/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

#### I want to add a new part
POST http://localhost:8000/api/parts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "part_number": "123456",
    "original_part_number": "123456",
    "brand": "bmw",
    "name": "oil filter",
    "category_id": 65,
    "unit_price": 12.34,
    "currency": "EUR",
    "quantity": 1
}
#### I want to see exists parts
GET http://localhost:8000/api/parts
Content-Type: application/json
Authorization: Bearer {{auth_token}}


###### I want to add parts to service
POST http://localhost:8000/api/services/01944076-5930-71ee-a54a-72f59edb2ae8/parts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

[{
    "part_id": "01944077-577e-7140-9e02-52335b863ec7",
    "quantity": 1
}]
####

Purchase
    id
    item_type
    item_id
    quantity
    unit_price
    shop
    created_at



//
// Car
// -> buy part for car
// -> buy service for car
// -> link part with service


// Choose car
//  -> add part
//     -> part number, original part number, brand, name, category, price, currency, quantity, shop, created_at
//  -> add service
//     -> service name, price, currency, shop, created_at
//     -> add part to service
//        -> part number, original part number, brand, name, category, price, currency, quantity, shop, created_at
//     -> choose existing part


// Part   -> (add part) -> Part status = "stock"
// Service -> (add part) -> Part status = "installed"
// Service -> (choose existing part) -> Part status = "installed"

